version: '2'
services:
  server:
    build: ./server_dock
    ports:
      - "5000:5000"
  client:
    depends_on:
      - server
    build: ./client_dock
    command: bash -c "sleep 10 && bash ./wait-for-it.sh server:5000 -- python3 ./client.py"
    stdin_open: true
    tty: true
    network_mode: service:server
